#Estrada Crespo Karla Julieta - Ejericio1 (Ficha de identificacion)
#Ficha de usuario

#Ingresa datos
print("Bienvenido a la ficha de identificacion")
nombre = input("Ingresa tu nombre:\n ")
nombre = str(nombre)
print(type(nombre))
noTel = input("Ingresa tu numero de telefono:\n ")
noTel = int(noTel)
print(type(noTel))
dir = input("Ingresa tu direccion:\n ")
dir = str(dir)
print(type(dir))
edad = input("Ingresa tu edad:\n ")
edad = int(edad)
print(type(edad))
nacionalidad = input("Ingresa tu nacionalidad:\n ")
nacionalidad = str(nacionalidad)
print(type(nacionalidad))
fechaNa = input("Ingresa tu fecha de nacimiento:\n ")
fechaNa = str(fechaNa)
print(type(fechaNa))
altura = input("Ingresa tu altura:\n ")
altura = float(altura)
print(type(altura))
peso = input("Ingresa tu peso:\n ")
peso = float(peso)
print(type(peso))

#Imprime datos
print("\nEl nombre es: ", nombre)
print("El telefono es: ", noTel)
print("La direccion es: ", dir)
print("La edad es: ", edad)
print("La nacionalidad es: ", nacionalidad)
print("La fecha de nacimiento es: ", fechaNa)
print("La altura es: ", altura)
print("El peso es: ", peso)